name: literexia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  flutter_screenutil: ^5.9.3
  lottie: ^3.3.1
  shared_preferences: ^2.5.2
  sqflite: ^2.4.1
  animated_text_kit: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Bird.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo_freground.png"

flutter:
  assets:
    - assets/icons/
    - assets/images/
    - assets/icons/Home.png
    - assets/icons/Home-inactive.png
    - assets/icons/Progress.png
    - assets/icons/Progress-active.png
    - assets/icons/Profile-inactive.png
    - assets/icons/Chatbot.png
    - assets/icons/chatbot-inactive.png
    - assets/icons/Profile.png
    - assets/images/logo.png
    - assets/icons/medal.png
    - assets/icons/ph.png
    - assets/images/profileimg.png
    - assets/images/badge1.png
    - assets/images/badge2.png
    - assets/images/badge3.png
    - assets/images/badge4.png
    - assets/images/badge5.png
    - assets/images/badge6.png
    - assets/images/teacher.png
    - assets/icons/greatjob.png
    - assets/icons/progressStar.png
    - assets/icons/boyprogress.png
    - assets/icons/book.png
    - assets/animation/LoadingTop.json
    - assets/animation/Background.json
    - assets/images/Bird.png
    - assets/images/Assistive Tools.png
    - assets/images/Performance Monitoring.png
    - assets/images/Performance Monitoring.png

  fonts:
    - family: Bubblegum
      fonts:
        - asset: assets/fonts/Bubblegum.ttf
    - family: Bungee
      fonts:
        - asset: assets/fonts/Bungee-Regular.ttf
    - family: Atkinson
      fonts:
        - asset: assets/fonts/AtkinsonHyperlegible-Bold.ttf
        - asset: assets/fonts/AtkinsonHyperlegible-BoldItalic.ttf
        - asset: assets/fonts/AtkinsonHyperlegible-Italic.ttf
        - asset: assets/fonts/AtkinsonHyperlegible-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans_SemiCondensed-Regular.ttf
        - asset: assets/fonts/OpenSans_SemiCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans_SemiCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans_SemiCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans_SemiCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans_SemiCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans_SemiCondensed-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans_SemiCondensed-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/OpenSans_SemiCondensed-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/OpenSans_SemiCondensed-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/OpenSans_SemiCondensed-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/OpenSans_SemiCondensed-ExtraBoldItalic.ttf
          weight: 800
          style: italic

  uses-material-design: true
